name: "All Pull Request Tests"

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  # We use a single job to ensure that all steps run in the same environment and
  # reduce the number of minutes used.
  pr-tests:
    # Don't run on draft PRs
    if: github.event.pull_request.draft == false
    # Timeout after 10 minutes
    timeout-minutes: 10
    # Define a matrix of PHP/WordPress versions to test against
    strategy:
      matrix:
        php: [8.1, 8.2, 8.3]
        wordpress: ["latest"]
        multisite: [false, true]
    runs-on: ubuntu-latest
    # Cancel any existing runs of this workflow
    concurrency:
      group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.ref }}-P${{ matrix.php }}-WP${{ matrix.wordpress }}-MS${{ matrix.multisite }}
      cancel-in-progress: true
    # Name the job in the matrix
    name: "PR Tests PHP ${{ matrix.php }} WordPress ${{ matrix.wordpress }} Multisite ${{ matrix.multisite }}"
    steps:
      - uses: actions/checkout@v4

      - name: Run General Tests
        # See https://github.com/alleyinteractive/action-test-general for more options
        uses: alleyinteractive/action-test-general@develop

      - name: Run PHP Tests
        # See https://github.com/alleyinteractive/action-test-php for more options
        uses: alleyinteractive/action-test-php@develop
        with:
          php-version: '${{ matrix.php }}'
          skip-audit: 'true'
          skip-wordpress-install: 'true'
          wordpress-version: '${{ matrix.wordpress }}'
          wordpress-multisite: '${{ matrix.multisite }}'
